### ISSUE TITLE
Frontend: Opcion para ofrecer/solicitar y/o chatear después de contribuir al pozo comun

### ISSUE THREAD

**Issue by mgutierrezc** [Leeps-Lab/ri_cda#2]
Una vez que el jugador envía los puntos al pozo común, se debería deshabilitar la opción de ofrecer/solicitar y/o chatear con los demás participantes? (ahora si permite, quizás el chat no se debería deshabilitar?)

Que sea configurable en el session config (crear una entrada boolean para esta opción)
Si no se permite después de contribuir, se debe avanzar a la siguiente pagina al contribuir

**Comment by mgutierrezc** [comment]
@veduve
- [x] Arreglar botones de ofrecer/solicitar #4 
- [ ] Una configuración: Interaccion y chat pueden ocurrir en simultaneo o primero chat luego interacciones sin chat #13
- [x] Actualizar dotación en frontend tras recibir puntos
- [x] Guardar transacciones exitosas #9
